// UI strings — EN / HI / MR. Operator-mediated console; the family-facing
// phrasing is generated by Claude in the family's language at explain-time
// (config.llm.languages). Keep keys flat and UI-only.

export const LANGS = ['en', 'hi', 'mr'];

export const STRINGS = {
  appName: { en: 'Setu', hi: 'सेतु', mr: 'सेतू' },
  tagline: {
    en: 'Missing Persons Console',
    hi: 'लापता व्यक्ति कंसोल',
    mr: 'खावेगिरी व्यक्ती कंसोल',
  },
  iLostSomeone: { en: 'I lost someone', hi: 'मैंने किसी को खोया', mr: 'मी कुणाला गमावलं' },
  iFoundSomeone: { en: 'I found someone', hi: 'मुझे कोई मिला', mr: 'मला कुणी सापडलं' },
  name: { en: 'Name', hi: 'नाम', mr: 'नाव' },
  age: { en: 'Age (approx)', hi: 'आयु (अनुमान)', mr: 'वय (अंदाजे)' },
  gender: { en: 'Gender', hi: 'लिंग', mr: 'लिंग' },
  male: { en: 'Male', hi: 'पुरुष', mr: 'पुरुष' },
  female: { en: 'Female', hi: 'महिला', mr: 'स्त्री' },
  state: { en: 'State of origin', hi: 'राज्य', mr: 'राज्य' },
  lastSeen: { en: 'Last seen near', hi: 'अंतिम बार देखा', mr: 'शेवटचे दिसले' },
  description: { en: 'Description', hi: 'विवरण', mr: 'वर्णन' },
  speak: { en: 'Speak', hi: 'बोलें', mr: 'बोला' },
  stop: { en: 'Stop', hi: 'रोकें', mr: 'थांबा' },
  search: { en: 'Find matches', hi: 'मिलान खोजें', mr: 'जुळवणी शोधा' },
  save: { en: 'Save & register', hi: 'सहेजें', mr: 'जतन करा' },
  matches: { en: 'Possible matches', hi: 'संभावित मिलान', mr: 'संभाव्य जुळण्या' },
  noMatches: { en: 'No likely matches in this center.', hi: 'इस केंद्र में कोई मिलान नहीं।', mr: 'या केंद्रात जुळणी नाही.' },
  hotspot: { en: 'ICCC hotspots', hi: 'आईसीसीसी हॉटस्पॉट', mr: 'आयसीसीसी हॉटस्पॉट' },
  opsMap: { en: 'Ops map', hi: 'ऑप्स मानचित्र', mr: 'ऑप्स नकाशा' },
  offline: { en: 'Offline — scoring on device', hi: 'ऑफलाइन — स्थानीय स्कोरिंग', mr: 'ऑफलाइन — स्थानिक स्कोअरिंग' },
  online: { en: 'Online', hi: 'ऑनलाइन', mr: 'ऑनलाइन' },
  semanticPending: { en: 'semantic pending (offline)', hi: 'सिमेंटिक लंबित', mr: 'सिमँटिक प्रलंबित' },
  back: { en: 'Back', hi: 'वापस', mr: 'मागे' },
  voiceUnsupported: { en: 'Voice not supported — type instead', hi: 'वॉइस असमर्थित — टाइप करें', mr: 'व्हॉइस असमर्थित — टाईप करा' },
};

export function t(lang, key) {
  const row = STRINGS[key];
  if (!row) return key;
  return row[lang] || row.en;
}
